# File:   00_data_munging.R
# Course: R: An Introduction (with RStudio)
# Some code snippets generated by the May24 2023 version of ChatGPT

# Import Necessary Packages ###############################
# Installs pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")

# Use pacman to load add-on packages as desired
pacman::p_load(pacman, dplyr)

# Basic Data Munging with Data Frames ###############################

# Create a sample data frame
data <- data.frame(
  id = c(1, 2, 3, 4, 5),
  name = c("John", "Jane", "Michael", "Emily", "David"),
  age = c(25, 30, NA, 35, 40),
  salary = c(50000, 60000, 55000, NA, 70000),
  stringsAsFactors = FALSE
)

# View the initial data
print(data)

typeof(data$salary)

salary <- data$salary
result <- numeric(length(data))

for (i in 1:length(salary)) {
  result[i] <- salary[i] * 2  # Example operation: doubling each element
}

# Remove rows with missing values
data_clean <- data %>%
  filter(!is.na(age) & !is.na(salary))

# View the cleaned data
print(data_clean)

# Calculate the average salary
avg_salary <- data_clean %>%
  summarise(avg_salary = mean(salary))

# View the average salary
print(avg_salary)

# Further Examples ##############################

# Create a sample data frame
data <- data.frame(
  id = c(1, 2, 3, 4, 5),
  name = c("John", "Jane", "Michael", "Emily", "David"),
  age = c(25, 30, NA, 35, 40),
  salary = c(50000, 60000, 55000, NA, 70000),
  stringsAsFactors = FALSE
)

# View the initial data
print(data)

# Remove rows with missing values
data_clean <- data %>%
  filter(!is.na(age) & !is.na(salary))

# View the cleaned data
print(data_clean)

# Calculate the average salary
avg_salary <- data_clean %>%
  summarise(avg_salary = mean(salary))

# View the average salary
print(avg_salary)

# Sort data by salary in descending order
data_sorted <- data_clean %>%
  arrange(desc(salary))

# View the sorted data
print(data_sorted)

# Add a new column for bonus based on salary
data_with_bonus <- data_sorted %>%
  mutate(bonus = salary * 0.1)

# View the data with the bonus column
print(data_with_bonus)

# Select specific columns
selected_columns <- data_with_bonus %>%
  select(id, name, salary, bonus)

# View the selected columns
print(selected_columns)

# Group data by age and calculate average salary within each group
grouped_data <- data_with_bonus %>%
  group_by(age) %>%
  summarise(avg_salary = mean(salary))

# View the grouped data
print(grouped_data)

# Join two data frames by a common column
additional_data <- data.frame(
  id = c(1, 2, 3, 4, 5),
  department = c("HR", "Finance", "Marketing", "Sales", "IT"),
  stringsAsFactors = FALSE
)

merged_data <- data_with_bonus %>%
  left_join(additional_data, by = "id")

# View the merged data
print(merged_data)

# Even More Examples ##############################

# Load the dplyr package
library(dplyr)

# Create a sample data frame
data <- data.frame(
  id = c(1, 2, 3, 4, 5),
  name = c("John", "Jane", "Michael", "Emily", "David"),
  age = c(25, 30, NA, 35, 40),
  salary = c(50000, 60000, 55000, NA, 70000),
  gender = c("M", "F", "M", "F", "M"),
  stringsAsFactors = FALSE
)

# View the initial data
print(data)

# Filter rows based on a condition
filtered_data <- data %>%
  filter(salary > 55000)

# View the filtered data
print(filtered_data)

# Replace missing values with a default value
data_filled <- data %>%
  mutate(age = ifelse(is.na(age), 0, age))

# View the data with filled values
print(data_filled)

# Create a new column based on conditional logic
data_with_category <- data %>%
  mutate(category = ifelse(salary >= 60000, "High", "Low"))

# View the data with the new category column
print(data_with_category)

# Remove duplicate rows
data_unique <- data %>%
  distinct()

# View the data with duplicate rows removed
print(data_unique)

# Rename columns
data_renamed <- data %>%
  rename(employee_id = id, annual_salary = salary)

# View the data with renamed columns
print(data_renamed)

# Create a summary table with multiple aggregate functions
summary_table <- data %>%
  group_by(gender) %>%
  summarise(
    avg_age = mean(age, na.rm = TRUE),
    max_salary = max(salary, na.rm = TRUE),
    min_salary = min(salary, na.rm = TRUE)
  )

# View the summary table
print(summary_table)

# Reshape data from wide to long format
wide_data <- data %>%
  select(id, name, age, gender) %>%
  pivot_wider(names_from = gender, values_from = age, names_prefix = "age_")

# View the wide data
print(wide_data)

# Reshape data from long to wide format
long_data <- wide_data %>%
  pivot_longer(cols = starts_with("age_"), names_to = "gender", values_to = "age")

# View the long data
print(long_data)

# Cleaning Things Up #######################

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L
