# File:   02_subset_analysis.R
# Course: R: An Introduction (with RStudio)
# Some code snippets generated by the May24 2023 version of ChatGPT
# Data was sourced from the Diabetes Dataset, available on Kaggle
# https://www.kaggle.com/datasets/mathchi/diabetes-data-set?resource=download

# During the data collection process, you and two other colleges are tasked
# with recording participants data. The software provided to you does not
# facilitate the simultaneous editing of a database by multiple users at one
# time. To worka round this constraint, each of you record your data and later
# save it in three individual CSV files, `01_data.csv`, `02_data.csv`, and 
# '03_data.csv`. Using these three files and the data analysis strategy you
# applied to the full dataset, conduct an analysis on the following:
# 1. Data set '01_data.csv',
# 2. Data set '02_data.csv',
# 3. Data set '03_data.csv',
# 4. Combine all three datasets into a single dataset.

# Organize your findings in a table and write up a brief discussion of your
# thoughts and findings.



# Import Necessary Packages ###############################
# Installs pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")

# Use pacman to load add-on packages as desired
pacman::p_load(pacman, dplyr, summarytools, cluster, ggplot2)

# 

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L
