# File:   d03_ealing_with_nans.R
# Course: R: An Introduction (with RStudio)
# Some code snippets generated by the May24 2023 version of ChatGPT
# Data was sourced from the Diabetes Dataset, available on Kaggle
# https://www.kaggle.com/datasets/mathchi/diabetes-data-set?resource=download
# All data subsets and alterations were crafted from the initial dataset.

# Explanation ######################

# During the data collection process, the software you use to record
# the relevant patient data experiences the occasional glitch that isn't
# caught until after all of the patients have been processed.
# Your supervisor tasks you with exploring the possible statistical implications
# of the following four scenarios:
# 1. Remove any row that contains an invalid value
# 2. Replace the missing value in a given column with the mean of existing values.
# 3. Replace the missing value in a given column with the median of existing values.
# 4. Replace the missing value in a given column with the mode of existing values.

# Using the same statistical methods you used to explore the initial complete dataset,
# complete the same analysis for each of the four possibilities listed above.
# Organize your findings in a table and write up a brief discussion of your
# thoughts and findings.

# Sample code is provided for replacing all of the NaN values in a column
# based on a set operation. 
# NOTE: This process will need to be repeated for each column in the data, with
# the only exception being `Outcome`, which is not missing any values.

# Import Necessary Packages ###############################
# Installs pacman ("package manager") if needed
if (!require("pacman")) install.packages("pacman")

# Use pacman to load add-on packages as desired
pacman::p_load(pacman, dplyr, summarytools, cluster, ggplot2)

# Load the Data ###########################
data <- read.csv("~/su23/mcnair23_intro_to_r/data/incomplete_diabetes_dataset.csv")


# Mode function, I couldn't find a reliable built-in function
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

# Remove rows with any NaN values
data_without_na <- na.omit(data)

# Replace NaN values with mean of a column
data$column_with_nan_mean <- ifelse(is.nan(data$column_with_nan_mean), 
                                    mean(data$column_with_nan_mean, 
                                    na.rm = TRUE), data$column_with_nan_mean)

# Replace NaN values with mode of a column
data$column_with_nan_mode <- ifelse(is.nan(data$column_with_nan_mode),
                                    Mode(data$column_with_nan_mode), 
                                    data$column_with_nan_mode)

# Replace NaN values with median of a column
data$column_with_nan_median <- ifelse(is.nan(data$column_with_nan_median), 
                                      median(data$column_with_nan_median, 
                                      na.rm = TRUE), data$column_with_nan_median)

# Cleaning Things Up #######################

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L