# File:   01_if_else_switch.R
# Course: R: An Introduction (with RStudio)
# Based off of https://adv-r.hadley.nz/control-flow.html
# Some code snippets generated by the May24 2023 version of ChatGPT

# If Statements in R ########################################

# An if statement in R:
# if (condition) true_action

value <- 7
if (value == 7) {
  print("I know this value!")
}

# What if we want a "failing" condition?
new.value <- 6
if (new.value == 7) {
  print("I know this value!")
} else {
  print("That's an unknown value...")
}

# More Flexibility with Else If ########################

# A simple ifelse statement

x <- 3

result <- ifelse(x > 5, "x is greater than 5", "x is less than or equal to 5")
print(result)

# An ifelse with vector inputs

x <- c(2, 7, 4, 9)

result <- ifelse(x > 5, "greater", "less or equal")
print(result)

# An alternative equivalent for vectorized components

x <- 1:10
dplyr::case_when(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  is.na(x) ~ "???",
  TRUE ~ as.character(x)
)

# ifelse with nested conditions

x <- 10
y <- 7

result <- ifelse(x > 5, ifelse(y > 5, "both x and y are greater than 5", 
                                      "x is greater than 5 but y is not"), 
                                      "x is less than or equal to 5")
print(result)

# Including an if else for additional cases

x <- 5

if (x < 0) {
  print("x is negative")
} else if (x == 0) {
  print("x is zero")
} else {
  print("x is positive")
}

grade <- function(score) {
  if (score > 90) {
    "A"
  } else if (score > 80) {
    "B"
  } else if (score > 50) {
    "C"
  } else {
    "F"
  }
}

grade(89)

# Switch Statements in R ####################

# A basic switch case

x <- 2

result <- switch(x,
                 "case1" = "Value is 1",
                 "case2" = "Value is 2",
                 "case3" = "Value is 3",
                 "default" = "Value is not 1, 2, or 3"
)
print(result)

# Using a switch case with expressions

x <- "apple"

result <- switch(x,
                 "apple" = "Fruit: Apple",
                 "orange" = "Fruit: Orange",
                 "banana" = "Fruit: Banana",
                 "default" = "Unknown fruit"
)
print(result)

# Using switch cases with a "falling-through" behavior

legs <- function(x) {
  switch(x,
         cow = ,
         horse = ,
         dog = 4,
         human = ,
         chicken = 2,
         plant = 0,
         stop("Unknown input")
  )
}
legs("cow")
#> [1] 4
legs("dog")

# Another example of using switch cases with a "falling-through" behavior

x <- 2

result <- switch(x,
                 "case1" = "Value is 1",
                 "case2" = {
                   print("Value is 2")
                   print("Performing additional operations for case 2")
                 },
                 "case3" = "Value is 3",
                 "default" = "Value is not 1, 2, or 3"
)
print(result)

# Using switch case to return a function

x <- "addition"

operation <- switch(x,
                    "addition" = function(a, b) a + b,
                    "subtraction" = function(a, b) a - b,
                    "multiplication" = function(a, b) a * b,
                    "division" = function(a, b) a / b,
                    "default" = function(a, b) NULL
)

if (!is.null(operation)) {
  result <- operation(5, 3)
  print(result)
} else {
  print("Invalid operation")
}

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L

# Clear mind :)
