# File:   02_for_loops.R
# Course: R: An Introduction (with RStudio)
# Based off of https://adv-r.hadley.nz/control-flow.html
# Some code snippets generated by the May24 2023 version of ChatGPT

# For Loops ##############

# Basic for loop to iterate over a sequence

for (i in 1:5) {
  print(i)
}

# Iterating through a vector

fruits <- c("apple", "banana", "orange")

for (fruit in fruits) {
  print(fruit)
}

# Nesting an if statement into a for loop

for (i in 1:10) {
  if (i %% 2 == 0) {
    print(paste(i, "is even"))
  } else {
    print(paste(i, "is odd"))
  }
}

# Nesting for loops, let's look at iterating through a matrix

matrix <- matrix(1:9, nrow = 3)

for (i in 1:nrow(matrix)) {
  for (j in 1:ncol(matrix)) {
    print(matrix[i, j])
  }
}

# For loop with a fixed step (non-unitary)

for (i in seq(0, 10, by = 2)) {
  print(i)
}

# Setting a "stop" using `break`

for (i in 1:10) {
  if (i == 6) {
    break
  }
  print(i)
}

# Skipping a specific value using 'next'

for (i in 1:10) {
  if (i == 5) {
    next
  }
  print(i)
}

# Some Pitfalls of Using for Loops ###################

# Preallocate your data structure, otherwise your calculations will be slow.
# One way to void this is to use the vector function

means <- c(1, 50, 20)
out <- vector("list", length(means))
for (i in 1:length(means)) {
  out[[i]] <- rnorm(10, means[[i]])
}
typeof(out)
print(out)

# When using a range with a length (1:length(x)), you may encounter
# unintuitive errors, such as `x has length 0`

# This code will fail
means <- c()
out <- vector("list", length(means))
for (i in 1:length(means)) {
  out[[i]] <- rnorm(10, means[[i]])
}

1:length(means)

# To work around this, use `seq_along(x)`

seq_along(means)

out <- vector("list", length(means))
for (i in seq_along(means)) {
  out[[i]] <- rnorm(10, means[[i]])
}

# No more errors =)

# When iterating over S3 vectors, you may have issues. Loops typically strip
# the attributes, creating erroneous behavior.

xs <- as.Date(c("2020-01-01", "2010-01-01"))
for (x in xs) {
  print(x)
}

for (i in seq_along(xs)) {
  print(xs[[i]])
}

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L

# Clear mind :)