# File:   03_while_loops.R
# Course: R: An Introduction (with RStudio)
# Based off of https://adv-r.hadley.nz/control-flow.html
# Some code snippets generated by the May24 2023 version of ChatGPT

# While Loops in R #################

# A basic while loop 

i <- 1

while (i <= 5) {
  print(i)
  i <- i + 1
}

# while loop with a conditional

x <- 1

while (x <= 10) {
  if (x %% 2 == 0) {
    print(x)
  }
  x <- x + 1
}

# While Loop with a break Statement

x <- 1

while (TRUE) {
  if (x > 5) {
    break
  }
  print(x)
  x <- x + 1
}

# While loop with a logical condition

condition <- TRUE
count <- 0

while (condition) {
  print("Executing while loop...")
  count <- count + 1
  if (count >= 5) {
    condition <- FALSE
  }
}

# While loop with a nested if statement

x <- 1

while (x <= 10) {
  if (x %% 3 == 0) {
    print(paste(x, "is divisible by 3"))
  } else {
    print(x)
  }
  x <- x + 1
}

# While loop with a control statement

x <- 1

while (x <= 10) {
  print(x)
  x <- x + 1
  if (x == 6) {
    next
  }
}

# A Caution for While Loops #################

# The code below creates an infinite loop. Why could this be harmful?

# while (TRUE) {
#   # Code statements that will run indefinitely
#   print("This is an infinite loop!")
# }

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L
