# File:   04_control_flow_with_data.R
# Course: R: An Introduction (with RStudio)
# Based off of https://adv-r.hadley.nz/control-flow.html
# Some code snippets generated by the May24 2023 version of ChatGPT

# For Loops #################

# Processing columns of a DataFrame

data <- data.frame(x = c(1, 2, 3), y = c(4, 5, 6))
for (col in colnames(data)) {
  # Perform operations on each column of the data frame
  print(col)
  print(data[[col]])
}


# Applying a function to each element of a vector

data <- c(1, 2, 3, 4, 5)
result <- numeric(length(data))

for (i in 1:length(data)) {
  result[i] <- data[i] * 2  # Example operation: doubling each element
}

print(result)

# While Loops ########################

# Reading data from a file until a condition is met

data <- read.csv("~/mcnair23_intro_to_r/week_02/data/SOCR-HeightWeight.csv")
head(data)
row <- 1

while ((row <= nrow(data)) & (data[row, "Index"]) < 10) {
  # Process the data for each row until a condition is met
  print(data[row, ])
  row <- row + 1
}

# Filtering data based on a condition

data <- c(1, 3, 5, 2, 4)
filtered_data <- numeric()

i <- 1
while (i <= length(data)) {
  if (data[i] > 3) {
    filtered_data <- c(filtered_data, data[i])
  }
  i <- i + 1
}

print(filtered_data)

# Performing iterative calculations until convergence

x <- 0.5
tolerance <- 0.0001
iteration <- 1

while (abs(x^3 - 2) > tolerance) {
  x <- x - (x^3 - 2) / (3 * x^2)  # Applying Newton's method to find cube root of 2
  iteration <- iteration + 1
}

print(paste("Approximate cube root of 2:", x))
print(paste("Number of iterations:", iteration))

# Clear environment
rm(list = ls()) 

# Clear console
cat("\014")  # ctrl+L